### PR TITLE
Add tabulate package to represent cubes as strings.

### LINKED ISSUE #1: Use the tabulate package to format output
https://pypi.python.org/pypi/tabulate

### PR DESCRIPTION
**Pull request by jfunction**
Require the tabulate package. Reformat cube `__str__` related code to
make use of it.

One thing which was done in this commit that may seem strange is the
assertions in the `__str__` method of `base_cube.py`. These were added 
 to make headers more explicit for future programmers but they also serve
as cheap unit tests. They aren't necessary and could safely be
removed. The headers could be squashed into the table also, and with
`headers="firstrow"`. That way one would not need to return multiple
values.

Resolves #1

### CODE REVIEW

**Comment by sjperkins** [comment]
Thanks @jfunction! Could I convince you to rebase your branch ontop of master and resolve the conflicts? It should be easy, I think you just need to replace `dimval.extents` with `(dimval.lower_extent, dimval.upper_extent)` in `gen_dimension_table`.

**Comment by jfunction** [comment]
I did something. I'm not sure what. I thought that what I did was pull your master into my forks master, and rebase the tabulate branch over my updated master. When I pushed though, Github threw an error due to conflicts and convinced me to merge my remote branch before pushing again. 

I now see there are 2 commits which say the same thing and the history is a bit cluttered. I haven't done proper git in a while now and seem to be losing it...

**Comment by sjperkins** [comment]
@jfunction Can you squash the the commits into a single one? This involves rebasing

First make a clone of your repo so that you have a backup. Then checkout your branch and initiate a rebase:

```bash
$ git checkout jfunction/tabulate
$ git rebase -i master
```

This should open up an interactive rebase session which should show you something like this:

```bash
pick 7f9c704 Add tabulate package to represent cubes as strings.
pick bba77a5 Add tabulate package to represent cubes as strings.

# Rebase 9f5a4be..b5be776 onto 9f5a4be
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
```

Change all except the first `pick` directive to `squash` like so:

```bash
pick 7f9c704 Add tabulate package to represent cubes as strings.
squash bba77a5 Add tabulate package to represent cubes as strings.

# Rebase 9f5a4be..b5be776 onto 9f5a4be
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
```

Save the above file and exit. git will now start rebasing. It may ask you to resolve merge conflicts during the rebase operation. Once you've edited the file with merge conflicts

```bash
$ git add mergeconflictfile.py
$ git rebase --abort       # only if you made mistakes and want to pull out
$ git rebase --continue  # if you're happy with the changes
```

Once the rebase is complete you can replace the commits on github with a force push

```bash
$ git push origin function/tabulate --force-with-lease  # Less aggressive
$ git push origin function/tabulate --force                   # More aggressive
```

Either of the above are appropriate in this case I think

**Comment by jfunction** [comment]
@sjperkins - Sorry for the delay, that went suspiciously smoothly. The only thing that's irking me is the strange spacing removal I think my editor did around, for example, line 178 in `basecube.py`.

**Comment by sjperkins** [comment]
Thanks for the pull request!

**Comment by jfunction** [comment]
Cool - thanks for helping me out with rebase :+1:

**Comment by sjperkins** [comment]
@jfunction I've credited you in 0d033565a73f34a09fd94d526a06cb74882b5fce

**Comment by jfunction** [comment]
:smile:

**Pull request merged**
